### ISSUE TITLE
X.Prompt.MPD.hs issue - building with ghc 8.10.3

### ISSUE THREAD

**Issue by davama** [xmonad/xmonad-extras#29]
Hello,

I've noticed that [xmonad](https://github.com/xmonad/xmonad) and [xmonad-contrib ](https://github.com/xmonad/xmonad-contrib)have been getting a lot of updates recently and that ghc version was also bumped.

I attempted to build with  8.10.3 but i get an error:

```
xmonad-extras > [1 of 7] Compiling XMonad.Actions.Eval
xmonad-extras > [2 of 7] Compiling XMonad.Actions.Volume
xmonad-extras > [3 of 7] Compiling XMonad.Hooks.PerWindowKbdLayout
xmonad-extras > [4 of 7] Compiling XMonad.Prompt.Eval
xmonad-extras > [5 of 7] Compiling XMonad.Prompt.MPD
xmonad-extras >       
xmonad-extras > /home/dmacias/xmonad-git/xmonad-extras/XMonad/Prompt/MPD.hs:189:6: error:
xmonad-extras >     • Couldn't match type ‘X ComplFunction’
xmonad-extras >                      with ‘String -> IO [String]’
xmonad-extras >       Expected type: ComplFunction
xmonad-extras >         Actual type: X ComplFunction
xmonad-extras >     • Possible cause: ‘historyCompletionP’ is applied to too many arguments
xmonad-extras >       In the third argument of ‘mkXPrompt’, namely
xmonad-extras >         ‘(historyCompletionP (showXPrompt (MPDPrompt "Search: ") ==))’
xmonad-extras >       In a stmt of a 'do' block:
xmonad-extras >         mkXPrompt
xmonad-extras >           (MPDPrompt "Search") xp
xmonad-extras >           (historyCompletionP (showXPrompt (MPDPrompt "Search: ") ==))
xmonad-extras >           (\ s
xmonad-extras >              -> do io
xmonad-extras >                      $ runMPD
xmonad-extras >                          $ do clear
xmonad-extras >                               ....
xmonad-extras >                    return ())
xmonad-extras >       In the expression:
xmonad-extras >         do mkXPrompt
xmonad-extras >              (MPDPrompt "Search") xp
xmonad-extras >              (historyCompletionP (showXPrompt (MPDPrompt "Search: ") ==))
xmonad-extras >              (\ s
xmonad-extras >                 -> do io $ runMPD $ ...
xmonad-extras >                       ....)
xmonad-extras >     |      
xmonad-extras > 189 |     (historyCompletionP (showXPrompt (MPDPrompt "Search: ") ==))
xmonad-extras >     |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xmonad-extras >            
Completed 3 action(s).     

--  While building package xmonad-extras-0.15.3 (scroll up to its section to see the error) using:
      /home/dmacias/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0 build lib:xmonad-extras --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

> stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.10.3

xmonad builds fine with current master branch of xmonad and xmonad-contrib.

Any input is appreciated!

Thank you,
Dave

**Comment by liskin** [comment]
This is probably caused by https://github.com/xmonad/xmonad-contrib/commit/9d520dc88026b9b4197381ed30d1c613d262dd0f by @slotThe.

**Comment by davama** [comment]
@liskin 
@slotThe
Thank you for the quick response!

I can confirm that xmonad builds with #30

```
xmonad-extras > configure (lib)
xmonad-extras > Configuring xmonad-extras-0.15.3...
xmonad-extras > build (lib)
xmonad-extras > Preprocessing library for xmonad-extras-0.15.3..
xmonad-extras > Building library for xmonad-extras-0.15.3..
xmonad-extras > [1 of 7] Compiling XMonad.Actions.Eval
xmonad-extras > [2 of 7] Compiling XMonad.Actions.Volume
xmonad-extras > [3 of 7] Compiling XMonad.Hooks.PerWindowKbdLayout
xmonad-extras > [4 of 7] Compiling XMonad.Prompt.Eval
xmonad-extras > [5 of 7] Compiling XMonad.Util.Brightness
xmonad-extras >            
xmonad-extras > /home/dmacias/xmonad-git/xmonad-extras/XMonad/Util/Brightness.hs:72:1: warning: [-Wunused-imports]
xmonad-extras >     The import of ‘Data.Traversable’ is redundant
xmonad-extras >       except perhaps to import instances from ‘Data.Traversable’
xmonad-extras >     To import instances alone, use: import Data.Traversable()
xmonad-extras >    |       
xmonad-extras > 72 | import Data.Traversable (traverse)
xmonad-extras >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xmonad-extras > [6 of 7] Compiling XMonad.Util.WindowPropertiesRE
xmonad-extras > [7 of 7] Compiling XMonad.Prompt.MPD
xmonad-extras >            
xmonad-extras > copy/register
xmonad-extras > Installing library in /home/dmacias/Google-Drive/Linux/HOMEenv/dotfiles/xmonad/.stack-work/install/x86_64-linux-tinfo6/7ea3880f0ca38842062bd34eb9ffd7feb8ff56e10f92f8f3c516d2c025ca7da3/8.10.3/lib/x86_64-linux-ghc-8.10.3/xmonad-extras-0.15.3-6Y89DQSjSI6BfymSN7RNNr
xmonad-extras > Registering library for xmonad-extras-0.15.3..
Completed 3 action(s).     
Copying from /home/dmacias/Google-Drive/Linux/HOMEenv/dotfiles/xmonad/.stack-work/install/x86_64-linux-tinfo6/7ea3880f0ca38842062bd34eb9ffd7feb8ff56e10f92f8f3c516d2c025ca7da3/8.10.3/bin/xmonad to /home/dmacias/.local/bin/xmonad

Copied executables to /home/dmacias/.local/bin:
- xmonad
```

Thanks!

Closing
